#!/usr/bin/env python3
"""Apply lint fixes using a JSON log file.

Expected input format:
{
  "mistakes": [
    {
      "filename": "vala/src/file.vala",
      "line": 10,
      "column": 3,
      "level": "error",
      "message": "...",
      "ruleId": "space-before-paren"
    }
  ]
}

This script focuses on deterministic, low-risk fixes:
- use-of-tabs
- trailing-whitespace
- ellipsis (... -> …)
- double-spaces (collapse internal runs of spaces)
- no-space (spaces around operators)
- space-before-paren
- line-length (best effort, line split at commas)
- trailing-newlines (ensure exactly one newline at EOF)

Rules that require scope/semantic analysis (`naming-convention`) or are
intentional annotations (`note`) are reported as needing manual review and
are not auto-modified.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple


# Single-character operators the "Expected spaces around operators" lint may
# flag. Used to locate the operator the linter is complaining about.
OP_CHARS = set("+-*/%=<>!&|^")

# Rules that are safe to auto-fix. Rules outside this set (and the manual
# set below) are reported as unsupported.
AUTO_FIX_RULES = {
    "use-of-tabs",
    "trailing-whitespace",
    "ellipsis",
    "double-spaces",
    "no-space",
    "space-before-paren",
    "line-length",
    "trailing-newlines",
}

# Rules that are understood but deliberately left for manual review.
MANUAL_RULES = {
    "naming-convention": "requires scope-aware rename",
    "note": "intentional annotation (TODO)",
}


@dataclass(frozen=True)
class Mistake:
    filename: str
    line: int
    column: int
    level: str
    message: str
    rule_id: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fix lint errors from a JSON report.")
    parser.add_argument(
        "--log",
        default="lint.json",
        help="Path to lint JSON report (default: lint.json)",
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Repository root (default: current directory)",
    )
    parser.add_argument(
        "--line-length",
        type=int,
        default=120,
        help="Maximum line length for best-effort wrapping (default: 120)",
    )
    parser.add_argument(
        "--tab-width",
        type=int,
        default=4,
        help="Spaces used to replace tab characters (default: 4)",
    )
    parser.add_argument(
        "--include-generated",
        action="store_true",
        help="Also process build/ generated files (skipped by default)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would change without writing files",
    )
    return parser.parse_args()


def normalize_path(raw: str) -> str:
    path = raw.strip()
    while path.startswith("./"):
        path = path[2:]
    if path.startswith(".vala/"):
        path = "vala/" + path[len(".vala/"):]
    return path


# Generated paths (meson build dirs, vendored build output) are not worth
# editing because they are regenerated by the build system.
GENERATED_RE = re.compile(
    r"(?:^|/)(?:build|builddir[^/]*|meson-private|sanity_check_for_vala)(?:/|$)"
)
GENERATED_HIDDEN_RE = re.compile(r"^\.(?:build|builddir)")


def is_generated(path: str) -> bool:
    return bool(GENERATED_RE.search(path) or GENERATED_HIDDEN_RE.match(path))


def load_mistakes(log_path: Path) -> List[Mistake]:
    try:
        data = json.loads(log_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"Log file not found: {log_path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {log_path}: {exc}")

    if isinstance(data, dict):
        items = data.get("mistakes", [])
    elif isinstance(data, list):
        items = data
    else:
        raise SystemExit("Unsupported lint JSON format: expected object or list")

    mistakes: List[Mistake] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        filename = normalize_path(str(item.get("filename", "")).strip())
        if not filename:
            continue
        try:
            line = int(item.get("line", 0))
            column = int(item.get("column", 1))
        except (TypeError, ValueError):
            continue
        rule_id = str(item.get("ruleId", "")).strip()
        if not rule_id:
            continue
        mistakes.append(
            Mistake(
                filename=filename,
                line=max(1, line),
                column=max(1, column),
                level=str(item.get("level", "")).strip(),
                message=str(item.get("message", "")).strip(),
                rule_id=rule_id,
            )
        )
    return mistakes


def rule_key_order(rule_id: str) -> int:
    # Apply whitespace normalization first, then targeted spacing, then wrapping.
    order = {
        "use-of-tabs": 0,
        "trailing-whitespace": 1,
        "double-spaces": 2,
        "ellipsis": 3,
        "no-space": 4,
        "space-before-paren": 5,
        "line-length": 6,
        "trailing-newlines": 7,
    }
    return order.get(rule_id, 99)


def fix_space_before_paren(line: str) -> str:
    # Convert foo( -> foo ( and also generic/cast closers >( -> > (
    # to satisfy lints such as typeof(string) and HashTable<K, V>(...).
    updated = re.sub(r"([A-Za-z_][A-Za-z0-9_\.]*)\(", r"\1 (", line)
    updated = re.sub(r"([>\]\)])\(", r"\1 (", updated)
    return updated


def fix_line_length(line: str, max_len: int) -> List[str]:
    if len(line) <= max_len:
        return [line]

    indent_match = re.match(r"\s*", line)
    indent = indent_match.group(0) if indent_match else ""

    cutoff = max_len
    break_candidates = [
        line.rfind(", ", 0, cutoff),
        line.rfind(" + ", 0, cutoff),
        line.rfind(" && ", 0, cutoff),
        line.rfind(" || ", 0, cutoff),
    ]
    split_at = max(break_candidates)

    if split_at <= len(indent) + 8:
        # Fallback: split long string literal by concatenation.
        first_quote = line.find('"')
        last_quote = line.rfind('"')
        if first_quote >= 0 and last_quote > first_quote + 1:
            available = max_len - (first_quote + 2)
            if available > 20:
                content = line[first_quote + 1:last_quote]
                split_pos = content.rfind(" ", 0, available)
                if split_pos > 10:
                    left_content = content[:split_pos]
                    right_content = content[split_pos + 1:]
                    left = line[: first_quote + 1] + left_content + '" +'
                    right = (
                        indent
                        + " " * 4
                        + '"'
                        + right_content
                        + '"'
                        + line[last_quote + 1:]
                    )
                    return [left.rstrip(), right.rstrip()]
        return [line]

    if line[split_at:split_at + 2] == ", ":
        left = line[: split_at + 1].rstrip()
        right = line[split_at + 2:].lstrip()
    else:
        left = line[: split_at + 2].rstrip()
        right = line[split_at + 3:].lstrip()

    if not right:
        return [line]

    continuation = indent + " " * 4 + right
    return [left, continuation]


def _nearest_nonspace(s: str, i: int, direction: int) -> str:
    j = i
    while 0 <= j < len(s) and s[j] in " \t":
        j += direction
    return s[j] if 0 <= j < len(s) else ""


def _should_space_operator(op: str, leftch: str, rightch: str) -> bool:
    # Never split multi-character operators (==, !=, <=, >=, +=, ->, &&, etc.)
    if leftch in OP_CHARS or rightch in OP_CHARS:
        return False
    # Avoid unary plus/minus (e.g. "(-1)") and signed numeric literals by
    # requiring an operand-like neighbour on the left.
    if op in "+-":
        if not (leftch.isalnum() or leftch in ")]}"):
            return False
    if not leftch or not rightch:
        return False
    return True


def fix_no_space(line: str, columns: List[int]) -> str:
    """Insert single spaces around binary operators flagged by column."""
    op_indices: List[int] = []
    for c in columns:
        for cand in (c - 1, c - 2):
            if 0 <= cand < len(line) and line[cand] in OP_CHARS and cand not in op_indices:
                op_indices.append(cand)
                break
    if not op_indices:
        return line

    out = line
    offset = 0
    for idx in sorted(set(op_indices)):
        i = idx + offset
        if i < 0 or i >= len(out):
            continue
        op = out[i]
        leftch = _nearest_nonspace(out, i - 1, -1)
        rightch = _nearest_nonspace(out, i + 1, 1)
        if not _should_space_operator(op, leftch, rightch):
            continue

        before = out[:i]
        after = out[i + 1:]
        op_str = op
        if before and before[-1] not in " \t":
            op_str = " " + op_str
        if after and after[0] not in " \t":
            op_str = op_str + " "
        diff = len(op_str) - 1
        out = before + op_str + after
        offset += diff
    return out


def fix_double_spaces(line: str, columns: List[int]) -> str:
    """Collapse runs of 2+ internal spaces (the ones containing flagged columns)."""
    out = line
    offset = 0
    for c in sorted(set(columns)):
        i = c - 1 + offset
        if i < 0 or i >= len(out) or out[i] != " ":
            continue
        s = i
        while s > 0 and out[s - 1] == " ":
            s -= 1
        if s == 0:
            # leading indentation, not what the lint targets
            continue
        e = i
        while e < len(out) and out[e] == " ":
            e += 1
        if e - s >= 2:
            out = out[:s] + " " + out[e:]
            offset -= (e - s - 1)
    return out


def apply_fixes_to_file(
    file_path: Path,
    mistakes: List[Mistake],
    max_len: int,
    tab_width: int,
) -> Tuple[bool, Dict[str, int]]:
    stats: Dict[str, int] = defaultdict(int)
    if not file_path.exists() or not file_path.is_file():
        stats["missing-files"] += 1
        return False, stats

    lines = file_path.read_text(encoding="utf-8").splitlines(keepends=False)

    # Separate whole-file rules from per-line rules.
    trailing_newline_mistakes: List[Mistake] = []
    manual: List[Mistake] = []
    by_line: Dict[int, List[Mistake]] = defaultdict(list)
    for m in mistakes:
        if m.rule_id == "trailing-newlines":
            trailing_newline_mistakes.append(m)
        elif m.rule_id in MANUAL_RULES:
            manual.append(m)
        elif m.rule_id in AUTO_FIX_RULES:
            by_line[m.line - 1].append(m)
        else:
            stats["unsupported-rules"] += 1

    changed = False

    # Work from bottom to top so line-length splits keep lower indices valid.
    for idx in sorted(by_line.keys(), reverse=True):
        if idx < 0 or idx >= len(lines):
            stats["out-of-range"] += 1
            continue

        line_mistakes = by_line[idx]
        line_mistakes.sort(key=lambda m: (rule_key_order(m.rule_id), m.column))

        original = lines[idx]
        updated = original

        for m in line_mistakes:
            if m.rule_id == "use-of-tabs":
                updated = updated.replace("\t", " " * tab_width)
            elif m.rule_id == "trailing-whitespace":
                updated = updated.rstrip()
            elif m.rule_id == "ellipsis":
                updated = updated.replace("...", "…")
            elif m.rule_id == "double-spaces":
                updated = fix_double_spaces(updated, [mm.column for mm in line_mistakes if mm.rule_id == "double-spaces"])
            elif m.rule_id == "no-space":
                cols = [mm.column for mm in line_mistakes if mm.rule_id == "no-space"]
                updated = fix_no_space(updated, cols)
            elif m.rule_id == "space-before-paren":
                updated = fix_space_before_paren(updated)

        if updated != original:
            lines[idx] = updated
            changed = True
            # count the contributing rules (dedup by rule on this line)
            for m in line_mistakes:
                if m.rule_id in ("use-of-tabs", "trailing-whitespace", "ellipsis",
                                 "double-spaces", "no-space", "space-before-paren"):
                    stats[m.rule_id] += 1

        # line-length is applied last since it can expand one line into many.
        ll_mistakes = [m for m in line_mistakes if m.rule_id == "line-length"]
        if ll_mistakes:
            wrapped = fix_line_length(lines[idx], max_len)
            if len(wrapped) > 1:
                lines[idx:idx + 1] = wrapped
                changed = True
                stats["line-length"] += 1

    # Ensure exactly one trailing newline (handles "Missing newline at end of file"
    # and collapses extra blank lines at EOF).
    if trailing_newline_mistakes:
        stats["trailing-newlines"] += len(trailing_newline_mistakes)
        changed = True  # splitlines drops the final newline; rebuilt content below
        # guarantees a single trailing newline.

    if manual:
        for m in manual:
            stats[f"manual:{m.rule_id}"] += 1

    if changed:
        # Normalise trailing blank lines to a single trailing newline.
        while len(lines) > 1 and lines[-1] == "":
            lines.pop()
        file_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return changed, stats


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    log_path = Path(args.log)
    if not log_path.is_absolute():
        log_path = (root / log_path).resolve()

    mistakes = load_mistakes(log_path)
    if not mistakes:
        print("No mistakes found in lint log.")
        return 0

    by_file: Dict[str, List[Mistake]] = defaultdict(list)
    skipped_generated = 0
    for m in mistakes:
        if not args.include_generated and is_generated(m.filename):
            skipped_generated += 1
            continue
        by_file[m.filename].append(m)

    total_stats: Dict[str, int] = defaultdict(int)
    changed_files = 0

    for rel_path, file_mistakes in sorted(by_file.items()):
        file_path = (root / rel_path).resolve()

        if args.dry_run:
            print(f"[DRY RUN] Would process: {rel_path} ({len(file_mistakes)} issues)")
            continue

        changed, stats = apply_fixes_to_file(
            file_path=file_path,
            mistakes=file_mistakes,
            max_len=args.line_length,
            tab_width=args.tab_width,
        )
        if changed:
            changed_files += 1
        for key, value in stats.items():
            total_stats[key] += value

    print(f"Processed files: {len(by_file)}")
    print(f"Changed files: {changed_files}")
    if skipped_generated:
        print(f"Skipped generated files: {skipped_generated} issues")
    if total_stats:
        print("Applied fixes:")
        for key in sorted(total_stats.keys()):
            print(f"  {key}: {total_stats[key]}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())