name: Compile test

on:
  push:
  pull_request:

jobs:
  build test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # Install standard build tools and existing libraries
          sudo apt-get install -y \
            valac meson ninja-build pkg-config \
            libgtk-4-dev libjson-glib-dev network-manager \
            shellcheck gobject-introspection libgirepository1.0-dev

          # Manually build and install gtk4-layer-shell (missing from Ubuntu repos on gh actions)
          git clone https://github.com/wmww/gtk4-layer-shell
          cd gtk4-layer-shell
          meson setup build --prefix=/usr
          ninja -C build
          sudo ninja -C build install
          cd ..

      - name: Shell syntax check
        run: |
          bash -n scripts/*.sh scripts/lib/*.sh

      - name: Shell lint (static analysis)
        run: |
          shellcheck scripts/*.sh scripts/lib/*.sh

      - name: Configure (release)
        run: |
          meson setup builddir-ci --buildtype=release

      - name: Compile
        run: |
          meson compile -C builddir-ci

      - name: Test binary
        run: |
          ./builddir-ci/vala/hypr-network-manager --help > /dev/null
